# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TempSaver
                                 A QGIS plugin
 Saves Temporary Layers to a Folder
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-11
        copyright            : (C) 2025 by VghnmlMClm
        email                : voughn.calma.086@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TempSaver class from file TempSaver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .temp_saver import TempSaver
    return TempSaver(iface)
